### ISSUE TITLE
这个程序要怎么打开？

### ISSUE THREAD

**Issue by Kroroero** [neko-para/HVAuto#1]
看了下好像不是油猴脚本那种用法？

**Comment by neko-para** [comment]
是的，是个本地的程序
使用Nodejs 12

**Comment by Kroroero** [comment]
> 是的，是个本地的程序
> 使用Nodejs 12

下好了node，cmd里node main.js出错
internal/modules/cjs/loader.js:834
  throw err;
  ^
Error: Cannot find module 'got'
Require stack:
- D:\HVAuto-master\hvauto.js
- D:\HVAuto-master\main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\HVAuto-master\hvauto.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\HVAuto-master\\hvauto.js', 'D:\\HVAuto-master\\main.js' ]
}

是不是我运行的方法错了

**Comment by neko-para** [comment]
要先执行`npm install`安装依赖

**Comment by Kroroero** [comment]
npm install 后显示了这个：

npm WARN hvauto@1.0.0 No repository field.
up to date in 1.135s
18 packages are looking for funding
  run `npm fund` for details

然后再node main.js后就没有反应了

**Comment by neko-para** [comment]
是的，用xxx=xxxxx; xxxx=xxxx的格式存放
使用之前要先在hv进入战斗，然后应该就可以了

**Comment by Kroroero** [comment]
使用是在cmd里node main吗
进入了战斗后使用也没反应，是ai.txt的预设没有设定攻击吗

**Comment by neko-para** [comment]
额预设的应该是能用的吧
要不你用用邮件发我你的QQ，我加你？
